embedding_model:
  name: nomic-embed-text

chroma_db:
  persist_directory: ./chroma_db
  collection_name: tcp_redbook

llm:
  ollama_model: deepseek-r1:14b
  gemini_model: gemini-2.5-flash
  # google_api_key: ${GOOGLE_API_KEY}

pdf_processor:
  chunk_size: 800
  chunk_overlap: 150

retrieval_qa:
  chain_type: stuff
  retrieve_k: 10

tts:
  model: tts_models/en/ljspeech/fast_pitch
  sample_rate: 22050